name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and fix linting
        run: |
          cd functions
          npm ci
          npm run lint --fix  # Add this line to fix linting issues

      - name: Deploy Firebase functions
        run: |
          cd functions
          npm run deploy

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_IAMTIF }}"
          channelId: live
          projectId: iamtif
